"""
REPORTING TOOLS
"""

import datetime
import glob


def write_lda_report(report_file):
	"""
	IN PROGRESS
	"""

	now = datetime.datetime.now()


	title = "LDA Automatic report"
	date = str(now.day)+"/"+str(now.month)+"/"+str(now.year)

	## Write file
	output_file = open(report_file, "w")

	## Write header
	output_file.write("\\documentclass[a4paper,9pt]{extarticle}\n\\usepackage[utf8]{inputenc}\n\\usepackage[T1]{fontenc}\n\\usepackage{graphicx}\n\\usepackage{xcolor}\n\\usepackage{tikz}\n\\usepackage{pgfplots}\n\\usepackage{amsmath,amssymb,textcomp}\n\\everymath{\\displaystyle}\n\n\\usepackage{times}\n\\renewcommand\\familydefault{\\sfdefault}\n\\usepackage{tgheros}\n\\usepackage[defaultmono,scale=0.85]{droidmono}\n\n\\usepackage{multicol}\n\\setlength{\\columnseprule}{0pt}\n\\setlength{\\columnsep}{20.0pt}\n\n\n\\usepackage{geometry}\n\\geometry{\na4paper,\ntotal={210mm,297mm},\nleft=10mm,right=10mm,top=10mm,bottom=15mm}\n\n\\linespread{1.3}\n\n\n% custom title\n\\makeatletter\n\\renewcommand*{\\maketitle}{%\n\\noindent\n\\begin{minipage}{0.4\\textwidth}\n\\begin{tikzpicture}\n\\node[rectangle,rounded corners=6pt,inner sep=10pt,fill=blue!50!black,text width= 0.75\\textwidth] {\\color{white}\\Huge \\@title};\n\\end{tikzpicture}\n\\end{minipage}\n\\hfill\n\\begin{minipage}{0.55\\textwidth}\n\\begin{tikzpicture}\n\\node[rectangle,rounded corners=3pt,inner sep=10pt,draw=blue!50!black,text width= 0.95\\textwidth] {\\LARGE \\@author};\n\\end{tikzpicture}\n\\end{minipage}\n\\bigskip\\bigskip\n}%\n\\makeatother\n\n% custom section\n\\usepackage[explicit]{titlesec}\n\\newcommand*\sectionlabel{}\n\\titleformat{\\section}\n{\\gdef\\sectionlabel{}\n\\normalfont\\sffamily\\Large\\bfseries\\scshape}\n{\\gdef\\sectionlabel{\\thesection\ }}{0pt}\n{\n\\noindent\n\\begin{tikzpicture}\n\\node[rectangle,rounded corners=3pt,inner sep=4pt,fill=blue!50!black,text width= 0.95\\columnwidth] {\\color{white}\\sectionlabel#1};\n\\end{tikzpicture}\n}\n\\titlespacing*{\\section}{0pt}{15pt}{10pt}\n\n\n% custom footer\n\\usepackage{fancyhdr}\n\\makeatletter\n\\pagestyle{fancy}\n\\fancyhead{}\n\\fancyfoot[C]{\\footnotesize \\textcopyright\\ \\@date\\ \\ \\@author}\n\\renewcommand{\\headrulewidth}{0pt}\n\\renewcommand{\\footrulewidth}{0pt}\n\\makeatother\n\n\n\\title{"+str(title)+"}\n\\author{FIXEME}\n\\date{"+str(date)+"}\n")
	output_file.write("\\begin{document}\n\\maketitle\n")


	## Write overview section
	## TODO: Adapt to the number of figures
	## TODO: Write some informations from files
	## generated by the R script
	output_file.write("\\section{Overview}\n")
	output_file.write("\\begin{center}\n")

	## Create a tabular for image in report
	list_of_scatterplot = glob.glob("output/images/scatterplot_*")
	output_file.write("\\begin{tabular}{c}\n")
	for image in list_of_scatterplot:
		image = image.split(".")
		image = image[0]
		output_file.write("\\includegraphics[scale=0.5]{\""+str(image)+"\"}\\\\\n")
	output_file.write("\\end{tabular}\n")

	## [IN PROGRESS: Write some informations from files]

	## [IN PROGRESS: Adapt to the number of figures]
	"""
	if(len(list_of_scatterplot) == 1):
		output_file.write("\\begin{tabular}{c}\n")
		output_file.write("\\includegraphics[scale=0.5]{\""+str(list_of_scatterplot[0])+"\"}")
		output_file.write("\\end{tabular}\n")
	"""
	output_file.write("\\end{center}\n")



	## Write LDA analysis section
	## Plot the figures
	## TODO: Adapt to the number of figures
	## TODO: Write some informations from files
	output_file.write("\\section{LDA description}\n")
	output_file.write("\\begin{center}\n")

	list_of_LDA = glob.glob("output/images/*_histogram.png")
	output_file.write("\\begin{tabular}{c}\n")
	for image in list_of_LDA:
		image = image.split(".")
		image = image[0]
		output_file.write("\\includegraphics[scale=0.5]{\""+str(image)+"\"}\\\\\n")
	output_file.write("\\end{tabular}\n")

	output_file.write("\\end{center}\n")


	## Write Representation section
	output_file.write("\\section{2D representation}\n")
	output_file.write("\\begin{center}\n")
	output_file.write("\\begin{tabular}{c}\n")
	output_file.write("\\includegraphics[scale=0.5]{\"output/images/LDA_visualisation\"}\\\\\n")
	output_file.write("scatterplot of the best two discriminant functions\n")
	output_file.write("\\end{tabular}\n")
	output_file.write("\\end{center}\n")


   	## Write footer
   	output_file.write("\\end{document}")
	output_file.close()


write_lda_report("trash.txt")